export const queryKeys = {
  all: ['query'] as const,
  themes: () => [...queryKeys.all, 'themes'] as const,
  theme: (slug: string) => [...queryKeys.themes(), slug] as const,
  popular: () => [...queryKeys.themes(), 'popular'] as const,
  seasonal: () => [...queryKeys.themes(), 'seasonal'] as const,
  search: (q: string) => [...queryKeys.all, 'search', q] as const,
  artists: () => [...queryKeys.all, 'artists'] as const,
  artist: (slug: string) => [...queryKeys.artists(), slug] as const,
  artistThemes: (slug: string) => [...queryKeys.artist(slug), 'themes'] as const,
  ratings: () => [...queryKeys.all, 'ratings'] as const,
  myRating: (slug: string) => [...queryKeys.ratings(), 'mine', slug] as const,
  favorites: () => [...queryKeys.all, 'favorites'] as const,
  friends: () => [...queryKeys.all, 'friends'] as const,
  friendRequests: () => [...queryKeys.friends(), 'requests'] as const,
  friendActivity: () => [...queryKeys.friends(), 'activity'] as const,
  follow: (username: string) => [...queryKeys.all, 'follow', username] as const,
  user: (username: string) => [...queryKeys.all, 'users', username] as const,
  me: () => [...queryKeys.all, 'users', 'me'] as const,
  notifications: () => [...queryKeys.all, 'notifications'] as const,
  notificationCount: () => [...queryKeys.notifications(), 'count'] as const,
  history: () => [...queryKeys.all, 'history'] as const,
  stats: () => [...queryKeys.all, 'stats'] as const,
  anime: (anilistId: number) => [...queryKeys.all, 'anime', anilistId] as const,
}
